### ISSUE TITLE
Hi, This project is  really interest things and good approach

### ISSUE THREAD

**Issue by inottimasamasa** [SwiftObjects/SwiftObjects#1]
Hi helje5.

Nice to meet you.
My name is Masato Inotsume.

I have been developped with The WebObjecs about 20 years ago.
I've loved The WebObjects.

So, I think The WOSession should do implement for sessionID sniffing.
WOSessionSotre.swift or wOSession.swift check sessionID and Remote-Address.

I'm not good at Swift , so I have no idea for implement,
But This project is feel so good !

I wanna do something for this project.

Thanks

**Comment by helje5** [comment]
Hi Masato, nice to hear to you like it.

Not quite sure what you mean by 

> The WOSession should do implement for sessionID sniffing

That we should use signed session IDs? Absolutely. If someone wants to contribute something, the project is open for PRs ;-)
